### ISSUE TITLE
Negative loss values

### ISSUE THREAD

**Issue by lleewwiiss** [LIVIAETS/boundary-loss#17]
From my understanding, the loss values could be negative if the predicted boundary is smaller or equal and enclosed by the real boundary, but in terms of optimisation would it be better to use an absolute value of the surface loss? 
If this understanding is incorrect, the negatives could be due to implementation errors when I converted it to TF

When combining it with other losses does it matter if the surface loss/overall loss is negative?

**Comment by Alloooshe** [comment]
@lleewwiiss  can you update this with your findings?

**Comment by HKervadec** [comment]
> When combining it with other losses does it matter if the surface loss/overall loss is negative?

It is not an issues, what matters at the end of the day is the gradient (when back-propagating). 

Since this is a minimization problem, a negative value won't be an issue. The only "issue" that some encounter, is that their code-base has the (unjustified) assumption that all losses should be positive and aim for 0. 

Of course, as for any combination of losses, you need to balance their different weights, which will vary between each application.

Hoel

**Comment by signalharbor27** [comment]
> 

From my experience, the negatives weren't an issue when you scaled the boundary loss by a factor of 1e-3 similar to in the original paper. I tried using the absolute value but don't think it makes sense.

**Comment by Alloooshe** [comment]
I have two more questions : 
1- if we are not minimizing loss to 0 then we are minimizing to -inf, I saw in another thread that the expected behavior is for the loss to become stable near some negative value, in this case, how do we determine if we reached a global or local optimum? 
2- how well boundary loss should work with unbalanced classes? is there some modification to weight classes?

**Comment by HKervadec** [comment]
>  1- if we are not minimizing loss to 0 then we are minimizing to -inf, I saw in another thread that the expected behavior is for the loss to become stable near some negative value, in this case, how do we determine if we reached a global or local optimum?

You can pre-compute the ideal value, by computing the boundary loss on the the ground truth. This value is different for all images, but you can then aggregative over the whole dataset ; just as you would aggregate over the loss over a single epoch.

>  2- how well boundary loss should work with unbalanced classes? is there some modification to weight classes?

Do you mean, imbalanced multi-class, or imbalanced binary (foreground and background only)?

For the binary imbalance case, that were our initial experiments, and it turned out to work quite easily.

For the multi-class, imbalanced case, you might need to 'boost' the smallest class, but not necessarily. The point of the boundary loss is that, as it works on the _boundary_ between the different classes, the size imbalanced has less impact. But only experience can tell.


Hoel

**Comment by Alloooshe** [comment]
thanks for your answer
my goal is to use boundary loss for multi-class, in my case I have background and surface, and then I have to detect defects on the surface, my labels contain all classes, when training, I can see that boundary loss works well with background and surface but IoU prediction values is 0 for all other "defect" classes, I tried to ignore the surface and background using the idc parameter in data loader but still I only get poor performance for the smaller defects.
I appreciate your opinion on my case !

**Comment by HKervadec** [comment]
> I have background and surface, and then I have to detect defects on the surface, **my labels contain all classes, when training,**

(Emphasis is mine.) Just to be explicit: do you mean that this is a fully supervised case, or that the lesion voxels have _both_ the surface and lesion label? I am asking as everything (losses and models in general) assume that you have a one-hot encoding (i.e., a single class per voxel). 

---
I am wondering, do you use the boundary loss alone, or in combination of another loss?

If your base loss is learning the surface "too hard", it might bias things beyond recovery. As such, tuning that initial loss might help.

Otherwise, you could try to use the boundary loss alone? I know this works for true multi-class cases (see [this screenshot](https://github.com/LIVIAETS/boundary-loss/blob/master/resources/acdc_bl.png)), but it has not yet been evaluated properly. 

Do not hesitate to post here your exact losses configuration, as well as scheduler (if relevant), and you could also show some images of your task (if you are allowed to).

Hoel
