### ISSUE TITLE
WMH dataset

### ISSUE THREAD

**Issue by andys0975** [LIVIAETS/boundary-loss#4]
Hello, I want to reproduce your results on WMH dataset, but I have waited the responses from the official email of MICCAI2017 challenge for two weeks. I wonder if you could share the download link?

**Comment by HKervadec** [comment]
Hey,

Thank you for the interest in our work. 

Sorry to hear that you have been waiting for two weeks. However, we are not allowed to share the data ourselves, as stated in the [confidentiality agreement](http://wmh.isi.uu.nl/details/#terms):
> The downloaded data sets, associated reference standard, or any data derived from these data sets, may not be given or redistributed under any circumstances to persons not belonging to the registered 
team.

I think this delay is due to the Christmas and new year holidays ; people should come back soon. You could also try to [contact them](http://wmh.isi.uu.nl/organizers/) directly.

Once you have the data, let me know if you have any trouble reproducing the results.
