### ISSUE TITLE
Whether this loss function can be applied to the partition of a hollow region, that is, a region with two boundaries

### ISSUE THREAD

**Issue by MrChenDingding** [LIVIAETS/boundary-loss#60]
Before posting, do check out the FAQ: https://github.com/LIVIAETS/boundary-loss#frequently-asked-question , the answer of your question might be there

**Comment by HKervadec** [comment]
(Sorry for the delayed reply. Somehow the Github notification for this repo are still broken on my side.)

This is a very short description of your setting, but my understanding is that yes, you can. This is due to the way the distance map is computed. Notice that the boundary loss was first tested on datasets with multiple lesions per slice, which would be closer to your setting. 

Feel free to provide examples, but you could easily test the result of the distance transfor (either [`one_hot2dist`](https://github.com/LIVIAETS/boundary-loss/blob/master/utils.py#L272) or the scipy [`distance_transform_edt](https://docs.scipy.org/doc/scipy/reference/generated/scipy.ndimage.distance_transform_edt.html) directly.

**Comment by MrChenDingding** [comment]
Thank you for your answer. I was greatly impressed by your article.
