### ISSUE TITLE
Loss for 3D Segmentation

### ISSUE THREAD

**Issue by bluesky314** [LIVIAETS/boundary-loss#7]
Hey Can you tell me what to alter in: class2one_hot,one_hot2dist and SurfaceLoss
to make it work for 3D segmentation tasks?

Thanks

**Comment by HKervadec** [comment]
`SurfaceLoss` and `class2one_hot` are trivial to modify, you simply need to add another axis (`bcwh` to `bcxyz`). For instance, the einsum in the surface loss could be modified as follow to handle both 2d and 3d:
```python
multipled = einsum("bc...,bc...->bc...", pc, dc)
```
Overall the code should already work (haven't tested), it is mostly the assertions that currently assume the image is in 2D that needs to be modified.

`one_hot2dist` should be fairly easy. On top of the extra dimension, you may want to use the sampling option in the [scipy function computing the distance map](https://docs.scipy.org/doc/scipy/reference/generated/scipy.ndimage.distance_transform_edt.html), since the resolution is probably not the same on all axises.
